---
language: python
services: docker

env:
  global:
    - COLLECTION_NAMESPACE: aschult5
    - COLLECTION_NAME: horizen
    - NODETRACKER_DIR: /mnt/nodetracker
  matrix:
    - TARGET_DISTRO: ubuntu1804
    - TARGET_DISTRO: ubuntu1604
    - TARGET_DISTRO: debian9

    # Test secure node creation
    - TARGET_DISTRO: ubuntu1804
      TARGET_PLAYBOOK: playbook-secure.yml
    - TARGET_DISTRO: ubuntu1604
      TARGET_PLAYBOOK: playbook-secure.yml
    - TARGET_DISTRO: debian9
      TARGET_PLAYBOOK: playbook-secure.yml

install:
  - pip install 'molecule[docker]'

before_script:
  # Move the collection into the required path.
  - cd ../
  - mkdir -p ansible_collections/$COLLECTION_NAMESPACE
  - mv ansible-collection-$COLLECTION_NAME ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

script:
  - molecule test

# notifications:
#   webhooks: https://galaxy.ansible.com/api/v1/notifications/
