---
- name: Include certificate vars
  include_vars: vars/certificate.yml

- name: Install systemd-cron for certificate renewal
  when: certbot_auto_renew
  apt: name=systemd-cron

- name: ufw allow http/tcp for cert generation
  when: certbot_create_if_missing | d()
  block:
  - name: ufw allow http
    ufw:
      rule: allow
      port: http
      proto: tcp
    notify: ufw enable
  rescue:
  - name: ufw allow 80
    ufw:
      rule: allow
      port: '80'
      proto: tcp
    notify: ufw enable
  tags:
    - firewall

- name: ufw allow http/tcp for cert generation
  when: certbot_create_if_missing | d()
  block:
  - name: ufw allow https
    ufw:
      rule: allow
      port: https
      proto: tcp
    notify: ufw enable
  rescue:
  - name: ufw allow 443
    ufw:
      rule: allow
      port: '443'
      proto: tcp
    notify: ufw enable
  tags:
    - firewall
