---
- name: Include certificate vars
  include_vars: vars/certificate.yml

- name: Install systemd-cron for certificate renewal
  when: certbot_auto_renew
  apt: name=systemd-cron

- name: Add certificate generation ports (http/https) to firewall allowed list
  when:
    - certbot_create_if_missing | d()
  set_fact:
    firewall_allowed_tcp_ports: "{{ (firewall_allowed_tcp_ports|d([]) + ['80', '443']) | unique }}"
  tags:
    - firewall
