---
- name: pip install docker
  pip: name=docker

- name: zcash-params volume info
  docker_volume_info:
    name: "{{ zend_zcash_srcvol }}"
    docker_host: "{{ zend_docker_host }}"
  register: zend_zcash_srcvol_info

- name: zen-fetch-params
  when: not zend_zcash_srcvol_info.exists
  docker_container:
    name: zen-fetch-params
    docker_host: "{{ zend_docker_host }}"
    image: zencash/zen-node:{{ zend_ver }}
    state: started
    command: zen-fetch-params
    detach: no
    volumes:
    - "{{ [zend_zcash_srcvol, '/mnt/zcash-params'] | join(':') }}"
    env:
      LOCAL_USER_ID: "{{ zend_user_id | quote }}"
      LOCAL_GRP_ID: "{{ zend_group_id | quote }}"
  register: zen_fetch_params
  until: zen_fetch_params is success
  retries: 5
  delay: 10
