---
# Dependencies
- name: Install ufw
  apt: name=ufw

- name: Disable IPv6
  lineinfile:
    path: /etc/default/ufw
    regexp: "^IPV6="
    line: "IPV6={{ ipv6enable }}"
  vars:
    ipv6enable: "{{ 'yes' if firewall_enable_ipv6|d() else 'no' }}"

# Firewall
- name: ufw allow outgoing
  ufw:
    policy: allow
    direction: outgoing
  notify: ufw enable

- name: ufw deny incoming
  ufw:
    policy: deny
    direction: incoming
  notify: ufw enable

- name: ufw limit ssh block
  block:
  - name: ufw limit ssh/tcp
    ufw:
      rule: limit
      port: ssh
      proto: tcp
    notify: ufw enable
  rescue:
  - name: ufw limit 22/tcp
    ufw:
      rule: limit
      port: '22'
      proto: tcp
    notify: ufw enable

- name: ufw allow zend/tcp
  ufw:
    rule: allow
    port: "{{ zend_port_p2p }}"
    proto: tcp
  notify: ufw enable
