---
- name: common
  hosts: all
  gather_facts: yes
  vars_files:
    - vars/common.yml

  handlers:
  - name: ufw enable
    ufw:
      state: enabled
      logging: "on"

  pre_tasks:
  - name: Install pip
    apt: name=python3-pip

  - name: Import firewall tasks
    import_tasks: tasks/firewall.yml
    tags: firewall

  - name: Import certificate (dependency) tasks
    import_tasks: tasks/certificate.yml
    tags: certificate

  roles:
  - role: geerlingguy.swap
    tags: swap

  - role: geerlingguy.certbot
    tags: certificate

  - role: geerlingguy.docker
    tags: always
