---
- hosts: all
  gather_facts: yes
  vars:
    zend_user_name: zenops
    zend_user_id: 9001
    zend_group_name: zenops
    zend_group_id: 9001
    zend_user_home: /home/{{ zend_user_name }}
    zend_user_shell: /bin/bash
    zend_user_groups_default: [ 'adm', 'systemd-journal', 'sudo' ]
    zend_user_groups: []
    zend_zcash_srcvol: zcash-params

  pre_tasks:
  - name: Create user groups
    group:
      name: "{{ item }}"
    loop: "{{ zend_user_groups_default + zend_user_groups }}"

  - name: Create user
    user:
      name: "{{ zend_user_name }}"
      uid: "{{ zend_user_id }}"
      comment: "{{ zend_user_name }}"
      shell: "{{ zend_user_shell }}"
      groups: "{{ (zend_user_groups_default + zend_user_groups) | join(',') }}"
      home: "{{ zend_user_home }}"

  - name: pip install docker
    pip: name=docker

  - name: zcash-params volume info
    docker_volume_info:
      name: "{{ zend_zcash_srcvol }}"
      docker_host: "{{ zend_docker_host }}"
    register: zend_zcash_srcvol_info

  - name: zen-fetch-params
    when: not zend_zcash_srcvol_info.exists
    docker_container:
      name: zen-fetch-params
      docker_host: "{{ zend_docker_host }}"
      image: zencash/zen-node:{{ zend_ver }}
      state: started
      command: zen-fetch-params
      detach: no
      volumes:
      - "{{ [zend_zcash_srcvol, '/mnt/zcash-params'] | join(':') }}"
      env:
        LOCAL_USER_ID: "{{ zend_user_id | quote }}"
        LOCAL_GRP_ID: "{{ zend_group_id | quote }}"
    register: zen_fetch_params
    until: zen_fetch_params is success
    retries: 5
    delay: 10

  roles:
  - role: geerlingguy.swap
    vars:
      swap_swappiness: '10'
    tags: swap

  - role: aschult5.zend
    tags: always
